image_encoder:
  type: grid_feats_vqa
  params:
    name: grid_feats_vqa
    model: X-152-region-dc5.yaml
    output_dir: ./save/models/regions_v2
    pretrained: true
    zero_init_residual: false
  resize: average_pooling
  num_features: 49