model_config:
  pilot:
    bert_model_name: bert-base-uncased
    direct_features_input: false
    modal_hidden_size: 2048
    text_hidden_size: 768
    image_encoder:
      type: grid_feats_vqa
      params:
        name: grid_feats_vqa
        pretrained: true
        pool_type: avg
        num_output_features: 1
        zero_init_residual: false
        model: R-50-updn.yaml
        output_dir: /work3/s194262/save/models/bounding_boxes
    text_encoder:
      type: any_transformer
      params:
        name: distilbert-base-uncased
        dim: 768
        num_hidden_layers: 12
        num_attention_heads: 12
    classifier:
      type: mlp
      params:
        in_dim: 2816
        out_dim: 2250
        hidden_dim: 2533
        num_layers: 2
    losses:
    - type: logit_bce
    model: pilot