model_config:
  pilot:
    # Type of bert model
    #bert_model_name: bert-base-uncased
    direct_features_input: false
    # Dimension of the embedding finally returned by the modal encoder
    modal_hidden_size: 2048
    # Dimension of the embedding finally returned by the text encoder
    text_hidden_size: 768
    # Used when classification head is activated
    num_labels: 10 # TODO: ?
    # Number of features extracted out per image
    num_features: 1



    # resnet50
    image_encoder:
      type: torchvision_resnet
      params:
        name: resnet50
        pretrained: true
        pool_type: avg
        num_output_features: 1
        zero_init_residual: false

    text_encoder:
      type: any_transformer
      params:
        name: distilbert-base-uncased
        dim: 768
        num_hidden_layers: 12
        num_attention_heads: 12




    classifier:
      type: mlp
      params:
        # 2048 + 768 in case of features
        # Modal_Dim * Number of embeddings + Text Dim
        in_dim: 2816
        out_dim: 2253 # target size for okvqa
        hidden_dim: 768
        num_layers: 1