config_version: 1.0
training:
  trainer: mmf
  seed: 35919603
  experiment_name: run
  max_updates: 100
  max_epochs: 1
  log_interval: 100
  logger_level: info
  log_format: simple
  log_detailed_config: false
  should_not_log: false
  colored_logs: true
  tensorboard: true
  wandb:
    enabled: false
    entity: null
    project: mmf
    name: run
    log_checkpoint: false
  batch_size: 32
  batch_size_per_device: null
  update_frequency: 1
  num_workers: 4
  fast_read: false
  dataset_size_proportional_sampling: true
  pin_memory: false
  persistent_workers: true
  checkpoint_interval: 1000
  evaluation_interval: 1000
  clip_gradients: false
  clip_norm_mode: all
  early_stop:
    enabled: false
    patience: 4000
    criteria: okvqa/roc_auc
    minimize: false
  lr_scheduler: true
  lr_steps: []
  lr_ratio: 0.1
  use_warmup: false
  warmup_factor: 0.2
  warmup_iterations: 1000
  device: cpu
  local_rank: null
  verbose_dump: false
  find_unused_parameters: false
  evaluate_metrics: false
  detect_anomaly: false
  fp16: false
  callbacks: []
  exit_on_nan_losses: true
trainer:
  type: lightning
  params:
    gpus: 1
    num_nodes: 1
    precision: 32
    deterministic: false
    benchmark: false
    max_steps: 22000
    max_epochs: null
    gradient_clip_val: 0.0
    num_sanity_val_steps: 0
    checkpoint_callback: true
    accumulate_grad_batches: 1
    val_check_interval: 1000
    log_every_n_steps: 100
    logger: false
    limit_val_batches: 1.0
    progress_bar_refresh_rate: 0
    resume_from_checkpoint: null
evaluation:
  metrics:
  - accuracy
  - binary_f1
  - roc_auc
  use_cpu: false
  predict: false
  predict_file_format: json
  reporter:
    type: file
    params: {}
model_config:
  pilot:
    bert_model_name: bert-base-uncased
    direct_features_input: false
    modal_hidden_size: 2048
    text_hidden_size: 768
    num_labels: 10
    num_features: 1
    image_encoder:
      type: resnet18
      params:
        name: resnet18
        pretrained: true
        pool_type: avg
        num_output_features: 1
        zero_init_residual: false
    text_encoder:
      type: transformer
      params:
        bert_model_name: bert-base-uncased
        hidden_size: 768
        num_hidden_layers: 12
        num_attention_heads: 12
        output_attentions: false
        output_hidden_states: false
        TOKENIZERS_PARALLELISM: true
    classifier:
      type: mlp
      params:
        in_dim: 2816
        out_dim: 2253
        hidden_dim: 768
        num_layers: 1
    losses:
    - type: logit_bce
    model: pilot
dataset_config:
  okvqa:
    data_dir: /Users/arond.jacobsen/.cache/torch/mmf/data/datasets
    depth_first: false
    fast_read: false
    use_images: true
    use_features: false
    zoo_requirements:
    - okvqa.defaults
    images:
      train:
      - okvqa/defaults/images/
      val:
      - okvqa/defaults/images/
      test:
      - okvqa/defaults/images/
    features:
      train:
      - okvqa/defaults/features/features_fc6/COCO_trainval2014.lmdb
      val:
      - okvqa/defaults/features/features_fc6/COCO_trainval2014.lmdb
      test:
      - okvqa/defaults/features/features_fc6/COCO_trainval2014.lmdb
    annotations:
      train:
      - okvqa/defaults/annotations/annotations/imdb_train.npy
      val:
      - okvqa/defaults/annotations/annotations/imdb_val.npy
      test:
      - okvqa/defaults/annotations/annotations/imdb_test.npy
    max_features: 100
    processors:
      text_processor:
        type: bert_tokenizer
        params:
          max_length: 14
          vocab:
            type: intersected
            embedding_name: glove.6B.300d
            vocab_file: okvqa/defaults/extras/vocabs/vocabulary_100k.txt
          preprocessor:
            type: simple_sentence
            params: {}
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          mask_probability: 0
          max_seq_length: 128
      answer_processor:
        type: vqa_answer
        params:
          num_answers: 10
          vocab_file: okvqa/defaults/extras/vocabs/answers_okvqa.txt
          preprocessor:
            type: simple_word
            params: {}
      image_processor:
        type: torchvision_transforms
        params:
          transforms:
          - type: Resize
            params:
              size:
              - 256
              - 256
          - type: CenterCrop
            params:
              size:
              - 224
              - 224
          - ToTensor
          - GrayScaleTo3Channels
          - type: Normalize
            params:
              mean:
              - 0.485
              - 0.456
              - 0.406
              std:
              - 0.12221994
              - 0.12145835
              - 0.14380469
      context_processor:
        type: fasttext
        params:
          download_initially: false
          max_length: 50
          model_file: wiki.en.bin
      ocr_token_processor:
        type: simple_word
        params: {}
      bbox_processor:
        type: bbox
        params:
          max_length: 50
    return_features_info: false
    use_ocr: false
    use_ocr_info: false
datasets: okvqa
model: pilot
config: configs/experiments/pilot/defaults.yaml
run_type: train
optimizer:
  allow_unused_parameters: false
  enable_state_sharding: false
  type: adam_w
  params:
    lr: 5.0e-05
    eps: 1.0e-08
scheduler:
  type: warmup_linear
  params:
    num_warmup_steps: 100
    num_training_steps: 100
env:
  cache_dir: /Users/arond.jacobsen/.cache/torch/mmf
  dataset_zoo: configs/zoo/datasets.yaml
  model_zoo: configs/zoo/models.yaml
  data_dir: /Users/arond.jacobsen/.cache/torch/mmf/data
  save_dir: ./save
  log_dir: ''
  report_dir: ''
  tensorboard_logdir: ''
  wandb_logdir: ''
  user_dir: ''
distributed:
  init_method: null
  rank: 0
  port: -1
  backend: nccl
  world_size: 1
  no_spawn: false
checkpoint:
  resume: false
  resume_file: null
  resume_best: false
  resume_pretrained: false
  resume_zoo: null
  zoo_config_override: false
  pretrained_state_mapping: {}
  max_to_keep: -1
  save_git_details: true
  reset:
    all: false
    optimizer: false
    counts: false
    fp16_scaler: false
multitasking:
  enabled: true
  type: size_proportional
  params: {}
start_rank: 0
device_id: 0
